// Prompt Library — Single source of truth for all prompts
// All text in Slovenian

export type PromptCategory = {
  id: string;
  label: string;
  icon: string;
  description: string;
};

export type Prompt = {
  id: string;
  categoryId: string;
  title: string;
  prompt: string;
  tool: "ai-chat" | "ai-besedila" | "ai-dokumenti" | "ai-prevajalnik" | "ai-grafika" | "ai-zvok";
  toolLabel: string;
  tags: string[];
};

export const promptCategories: PromptCategory[] = [
  {
    id: "poslovanje",
    label: "Poslovanje",
    icon: "Briefcase",
    description: "Poslovni načrti, pogodbe, predstavitve in korespondenca",
  },
  {
    id: "marketing",
    label: "Marketing",
    icon: "Megaphone",
    description: "Oglasi, kampanje, strategije in analiza trga",
  },
  {
    id: "e-trgovina",
    label: "E-trgovina",
    icon: "ShoppingCart",
    description: "Opisi izdelkov, ocene, pogosta vprašanja",
  },
  {
    id: "izobrazevanje",
    label: "Izobraževanje",
    icon: "GraduationCap",
    description: "Učni načrti, povzetki, kvizi in študijski vodniki",
  },
  {
    id: "kreativno-pisanje",
    label: "Kreativno pisanje",
    icon: "Feather",
    description: "Zgodbe, poezija, scenariji in dialogi",
  },
  {
    id: "druzbena-omrezja",
    label: "Družbena omrežja",
    icon: "Share2",
    description: "Instagram, LinkedIn, TikTok in YouTube vsebine",
  },
  {
    id: "e-posta",
    label: "E-pošta",
    icon: "Mail",
    description: "Prodajna pisma, glasila, sledilna sporočila",
  },
  {
    id: "seo-in-splet",
    label: "SEO in splet",
    icon: "Search",
    description: "Blog objave, meta opisi, ključne besede",
  },
  {
    id: "grafika",
    label: "Grafika",
    icon: "Image",
    description: "Opisi za generiranje slik z AI",
  },
  {
    id: "zvok",
    label: "Zvok",
    icon: "Volume2",
    description: "Scenariji za TTS, podkaste in voiceover",
  },
  {
    id: "produktivnost",
    label: "Produktivnost",
    icon: "ListChecks",
    description: "Zapiski sestankov, načrti projektov, opravila",
  },
  {
    id: "diy-zivljenjski-slog",
    label: "DIY in življenjski slog",
    icon: "Home",
    description: "Recepti, domači projekti, potovanja, fitnes",
  },
];

export const allPrompts: Prompt[] = [
  // ═══════════════════════════════════════════
  // POSLOVANJE (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "posl-01",
    categoryId: "poslovanje",
    title: "Poslovni načrt za startup",
    prompt: "Napiši strukturiran poslovni načrt za startup, ki se ukvarja z [opiši dejavnost]. Vključi povzetek, analizo trga, ciljno skupino, poslovni model, finančne projekcije za 3 leta in strategijo rasti.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["poslovni načrt", "startup", "strategija"],
  },
  {
    id: "posl-02",
    categoryId: "poslovanje",
    title: "Profesionalno poslovno pismo",
    prompt: "Napiši formalno poslovno pismo za [namen: ponudba/reklamacija/povpraševanje] naslovljeno na [podjetje/oseba]. Pismo naj bo vljudno, jedrnato in profesionalno. Vključi vse standardne elemente poslovnega pisma.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["poslovno pismo", "korespondenca", "formalno"],
  },
  {
    id: "posl-03",
    categoryId: "poslovanje",
    title: "SWOT analiza podjetja",
    prompt: "Pripravi celovito SWOT analizo za podjetje v panogi [panoga]. Podrobno opiši prednosti, slabosti, priložnosti in nevarnosti. Za vsako kategorijo navedi vsaj 5 točk z obrazložitvijo.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["SWOT", "analiza", "strategija"],
  },
  {
    id: "posl-04",
    categoryId: "poslovanje",
    title: "Elevator pitch",
    prompt: "Ustvari prepričljiv elevator pitch (30 sekund) za [izdelek/storitev]. Pitch naj odgovori: Kakšen problem rešujemo? Kako ga rešujemo? Zakaj smo boljši od konkurence? Kaj želimo od sogovornika?",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["pitch", "predstavitev", "prodaja"],
  },
  {
    id: "posl-05",
    categoryId: "poslovanje",
    title: "Pogodba o sodelovanju",
    prompt: "Pripravi osnutek pogodbe o poslovnem sodelovanju med podjetjema [podjetje A] in [podjetje B]. Vključi predmet pogodbe, obveznosti obeh strank, trajanje, plačilne pogoje, zaupnost in reševanje sporov.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["pogodba", "sodelovanje", "pravno"],
  },
  {
    id: "posl-06",
    categoryId: "poslovanje",
    title: "Ponudba za stranko",
    prompt: "Napiši profesionalno ponudbo za [storitev/izdelek] za stranko [ime stranke]. Vključi opis storitve, obseg dela, časovnico, ceno s popustom, plačilne pogoje in rok veljavnosti ponudbe.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["ponudba", "prodaja", "stranka"],
  },
  {
    id: "posl-07",
    categoryId: "poslovanje",
    title: "Analiza konkurence",
    prompt: "Pripravi podrobno analizo konkurence za [panoga/trg]. Identificiraj 5 glavnih konkurentov, analiziraj njihove prednosti in slabosti, cenovne strategije, tržne deleže in priložnosti za difereciacijo.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["konkurenca", "analiza", "trg"],
  },
  {
    id: "posl-08",
    categoryId: "poslovanje",
    title: "Predstavitev za investitorje",
    prompt: "Pripravi strukturo in vsebino za investitorsko predstavitev (pitch deck) za [podjetje/ideja]. Vključi: problem, rešitev, velikost trga, poslovni model, traction, ekipo, finančne projekcije in zahtevani znesek investicije.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["investitorji", "pitch deck", "financiranje"],
  },
  {
    id: "posl-09",
    categoryId: "poslovanje",
    title: "Opis delovnega mesta",
    prompt: "Napiši privlačen opis delovnega mesta za pozicijo [naziv delovnega mesta] v podjetju [ime podjetja]. Vključi opis podjetja, naloge in odgovornosti, zahtevane kompetence, kaj ponujamo in način prijave.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["zaposlovanje", "HR", "delovno mesto"],
  },
  {
    id: "posl-10",
    categoryId: "poslovanje",
    title: "Letno poročilo oddelka",
    prompt: "Napiši strukturirano letno poročilo za oddelek [ime oddelka]. Vključi povzetek dosežkov, ključne metrike in KPI-je, izzive in rešitve, primerjavo s cilji ter cilje za naslednje leto.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["poročilo", "letno", "KPI"],
  },

  // ═══════════════════════════════════════════
  // MARKETING (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "mark-01",
    categoryId: "marketing",
    title: "Strategija digitalne kampanje",
    prompt: "Pripravi celovito strategijo digitalne marketinške kampanje za [izdelek/storitev]. Vključi cilje kampanje, ciljno publiko, kanale (Google, Meta, LinkedIn), proračun, ključna sporočila, časovnico in KPI-je za merjenje uspeha.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["kampanja", "digitalni marketing", "strategija"],
  },
  {
    id: "mark-02",
    categoryId: "marketing",
    title: "Google Ads besedilo oglasa",
    prompt: "Napiši 5 različic besedila za Google Ads oglas za [izdelek/storitev]. Za vsako različico pripravi: naslov 1 (30 znakov), naslov 2 (30 znakov), naslov 3 (30 znakov) in opis (90 znakov). Uporabi močne CTA-je in ključne prednosti.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["Google Ads", "oglas", "PPC"],
  },
  {
    id: "mark-03",
    categoryId: "marketing",
    title: "Vsebinski koledar za mesec",
    prompt: "Pripravi vsebinski koledar za 1 mesec za blagovno znamko [ime] v panogi [panoga]. Za vsak teden določi 3 objave z: naslov, kratki opis vsebine, kanal (blog/Instagram/LinkedIn/newsletter) in cilj objave.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["vsebinski koledar", "načrtovanje", "vsebine"],
  },
  {
    id: "mark-04",
    categoryId: "marketing",
    title: "Persona kupca",
    prompt: "Ustvari podrobno persono idealnega kupca za [izdelek/storitev]. Vključi demografske podatke, psihografske lastnosti, bolečine in frustracije, cilje in želje, nakupovalne navade, uporabljene medije in argumente za nakup.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["persona", "ciljna skupina", "kupec"],
  },
  {
    id: "mark-05",
    categoryId: "marketing",
    title: "Facebook/Instagram oglas",
    prompt: "Napiši prepričljivo besedilo za Facebook/Instagram oglas za [izdelek/storitev]. Pripravi 3 različice: kratko (do 125 znakov), srednje (do 250 znakov) in dolgo (do 500 znakov). Vsaka naj vsebuje kljukico, prednosti in jasen CTA.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["Facebook", "Instagram", "oglas", "družbena omrežja"],
  },
  {
    id: "mark-06",
    categoryId: "marketing",
    title: "Pristajalna stran (landing page)",
    prompt: "Napiši vsebino za pristajalno stran za [izdelek/storitev]. Vključi: privlačen naslov, podnaslov, 3 ključne prednosti z ikonami, socialni dokaz (ocene), razdelek s pogostimi vprašanji in CTA. Vse v slovenščini.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["landing page", "pristajalna stran", "konverzija"],
  },
  {
    id: "mark-07",
    categoryId: "marketing",
    title: "PR sporočilo za medije",
    prompt: "Napiši profesionalno sporočilo za medije (press release) o [novica/dogodek]. Sledij strukturi: naslov, datum in kraj, uvodni odstavek (kdo, kaj, kdaj, kje, zakaj), jedro zgodbe, izjava direktorja, podatki o podjetju in kontakt.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["PR", "mediji", "sporočilo za javnost"],
  },
  {
    id: "mark-08",
    categoryId: "marketing",
    title: "Unique selling proposition",
    prompt: "Pomagaj mi definirati USP (unique selling proposition) za [podjetje/izdelek]. Analiziraj, kaj nas dela edinstvene, kakšne koristi prinašamo strankam in zakaj bi nas izbrali pred konkurenco. Predlagaj 5 različic USP-ja.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["USP", "pozicioniranje", "diferenciacija"],
  },
  {
    id: "mark-09",
    categoryId: "marketing",
    title: "Influencer outreach sporočilo",
    prompt: "Napiši personalizirano sporočilo za influencerja [ime/niša] za sodelovanje pri promociji [izdelek/storitev]. Sporočilo naj bo prijazno, kratko in naj jasno predstavi koristi sodelovanja. Pripravi 3 različice tona: formalno, sproščeno in navdušeno.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["influencer", "sodelovanje", "outreach"],
  },
  {
    id: "mark-10",
    categoryId: "marketing",
    title: "Rezultati kampanje — poročilo",
    prompt: "Pripravi predlogo poročila o rezultatih marketinške kampanje. Vključi: povzetek kampanje, cilji vs. rezultati, ključne metrike (doseg, klik, konverzije, ROI), analiza po kanalih, naučene lekcije in priporočila za naprej.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["poročilo", "kampanja", "rezultati", "ROI"],
  },

  // ═══════════════════════════════════════════
  // E-TRGOVINA (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "etrg-01",
    categoryId: "e-trgovina",
    title: "Opis izdelka za spletno trgovino",
    prompt: "Napiši privlačen opis izdelka za spletno trgovino: [ime izdelka]. Vključi privlačen naslov, kratki opis (2 stavka), podrobni opis (200 besed), ključne lastnosti (5 točk), specifikacije in SEO meta opis.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["opis izdelka", "e-trgovina", "prodaja"],
  },
  {
    id: "etrg-02",
    categoryId: "e-trgovina",
    title: "Pogosta vprašanja (FAQ)",
    prompt: "Pripravi 10 pogostih vprašanj in odgovorov za spletno trgovino, ki prodaja [vrsta izdelkov]. Vključi vprašanja o dostavi, vračilih, plačilnih metodah, garanciji, velikostih in materialih. Odgovori naj bodo jasni in prijazni.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["FAQ", "pogosta vprašanja", "e-trgovina"],
  },
  {
    id: "etrg-03",
    categoryId: "e-trgovina",
    title: "E-mail za zapuščeno košarico",
    prompt: "Napiši serijo 3 e-mailov za zapuščeno košarico v spletni trgovini [ime]. E-mail 1 (po 1 uri): prijazen opomnik. E-mail 2 (po 24 urah): poudarek na prednostih. E-mail 3 (po 72 urah): zadnja priložnost s popustom. Vključi CTA v vsakem.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["zapuščena košarica", "e-mail", "konverzija"],
  },
  {
    id: "etrg-04",
    categoryId: "e-trgovina",
    title: "Ocene in pričevanja",
    prompt: "Napiši 5 realističnih vzorčnih ocen za izdelek [ime izdelka]. Vsaka ocena naj vsebuje: ime kupca, oceno (4-5 zvezdic), naslov ocene in besedilo (2-3 stavki). Ocene naj izpostavljajo različne prednosti izdelka.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["ocene", "pričevanja", "socialni dokaz"],
  },
  {
    id: "etrg-05",
    categoryId: "e-trgovina",
    title: "Opisi kategorij izdelkov",
    prompt: "Napiši SEO-optimizirane opise za naslednje kategorije v spletni trgovini: [navedi kategorije]. Za vsako kategorijo pripravi naslov, kratki uvod (50 besed) in 3 ključne razloge za nakup. Uporabi naravne ključne besede.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["kategorije", "SEO", "e-trgovina"],
  },
  {
    id: "etrg-06",
    categoryId: "e-trgovina",
    title: "Navodila za uporabo izdelka",
    prompt: "Napiši jasna in razumljiva navodila za uporabo izdelka [ime izdelka]. Vključi: vsebino paketa, pripravo, korak-za-korakom navodila (oštevilčena), varnostna opozorila, nasvete za vzdrževanje in kontakt za podporo.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["navodila", "uporaba", "izdelek"],
  },
  {
    id: "etrg-07",
    categoryId: "e-trgovina",
    title: "Sezonska akcija — besedila",
    prompt: "Pripravi komplet besedil za sezonsko akcijo [praznik/sezona] v spletni trgovini. Vključi: naslov akcije, banner besedilo, 3 e-mail naslove, SMS sporočilo, pop-up besedilo in objavo za družbena omrežja. Vse v slovenščini.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["akcija", "sezona", "promocija"],
  },
  {
    id: "etrg-08",
    categoryId: "e-trgovina",
    title: "Primerjava izdelkov",
    prompt: "Pripravi pregledno primerjavo med [izdelek A] in [izdelek B]. Vključi tabelo s ključnimi lastnostmi, prednosti in slabosti vsakega, priporočilo glede na uporabnikov profil in zaključek. Bodi objektiven.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["primerjava", "izdelki", "pregled"],
  },
  {
    id: "etrg-09",
    categoryId: "e-trgovina",
    title: "Program zvestobe — opis",
    prompt: "Napiši opis programa zvestobe za spletno trgovino [ime]. Vključi: kako deluje (zbiranje točk), nivoji članstva (3 nivoji), koristi za člane, pogoji včlanitve in primer izračuna prihrankov. Ton naj bo navdušujoč.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["zvestoba", "program", "člani"],
  },
  {
    id: "etrg-10",
    categoryId: "e-trgovina",
    title: "Dobrodošlica novemu kupcu",
    prompt: "Napiši toplo dobrodošlico e-mail za novega kupca spletne trgovine [ime]. Vključi zahvalo za nakup, kaj lahko pričakuje (dostava), popust za naslednji nakup (10%), povabilo na družbena omrežja in kontakt za pomoč.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["dobrodošlica", "e-mail", "kupec"],
  },

  // ═══════════════════════════════════════════
  // IZOBRAŽEVANJE (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "izob-01",
    categoryId: "izobrazevanje",
    title: "Učni načrt za predmet",
    prompt: "Pripravi podroben učni načrt za predmet [ime predmeta] za [stopnja: osnovna/srednja šola/fakulteta]. Vključi cilje predmeta, tedenski razpored tem (15 tednov), metode poučevanja, način ocenjevanja in priporočeno literaturo.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["učni načrt", "predmet", "poučevanje"],
  },
  {
    id: "izob-02",
    categoryId: "izobrazevanje",
    title: "Povzetek učne snovi",
    prompt: "Napiši jedrnat povzetek naslednje učne snovi za lažje učenje: [prilepi snov ali opiši temo]. Povzetek naj vsebuje ključne koncepte, definicije, formule in primere. Uporabi alineje in poudarke za preglednost.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["povzetek", "učenje", "snov"],
  },
  {
    id: "izob-03",
    categoryId: "izobrazevanje",
    title: "Kviz za preverjanje znanja",
    prompt: "Pripravi kviz z 15 vprašanji za preverjanje znanja iz teme [tema]. Vključi: 5 vprašanj z izbirnimi odgovori (4 možnosti), 5 vprašanj pravilno/napačno in 5 kratkih odprtih vprašanj. Na koncu dodaj rešitve z obrazložitvami.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["kviz", "preverjanje", "vprašanja"],
  },
  {
    id: "izob-04",
    categoryId: "izobrazevanje",
    title: "Razlaga zahtevnega koncepta",
    prompt: "Razloži koncept [koncept] na preprost in razumljiv način, kot bi razlagal učencu brez predznanja. Uporabi analogije iz vsakdanjega življenja, primere in vizualne opise. Na koncu dodaj 3 vprašanja za preverjanje razumevanja.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["razlaga", "koncept", "poenostavitev"],
  },
  {
    id: "izob-05",
    categoryId: "izobrazevanje",
    title: "Študijski vodnik za izpit",
    prompt: "Pripravi študijski vodnik za izpit iz predmeta [predmet]. Vključi: seznam ključnih tem, kratke povzetke vsake teme, pomembne formule/definicije, nasvete za učenje, pogosta izpitna vprašanja in strategijo za reševanje izpita.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["študijski vodnik", "izpit", "priprava"],
  },
  {
    id: "izob-06",
    categoryId: "izobrazevanje",
    title: "Esej na dano temo",
    prompt: "Napiši strukturiran esej (800 besed) na temo [tema]. Esej naj vsebuje uvod s tezo, 3 argumente z dokazi in primeri, protiargument z zavrnitvijo in zaključek. Uporabi akademski slog pisanja.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["esej", "akademsko", "pisanje"],
  },
  {
    id: "izob-07",
    categoryId: "izobrazevanje",
    title: "Učne kartice (flashcards)",
    prompt: "Ustvari 20 učnih kartic za učenje snovi [tema/predmet]. Vsaka kartica naj ima sprednjo stran (vprašanje ali pojem) in zadnjo stran (odgovor ali razlaga). Kartice razporedi od osnovnih do zahtevnejših konceptov.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["učne kartice", "flashcards", "memoriranje"],
  },
  {
    id: "izob-08",
    categoryId: "izobrazevanje",
    title: "Načrt učne ure",
    prompt: "Pripravi podroben načrt učne ure (45 min) za temo [tema] za [razred/letnik]. Vključi: cilje ure, uvodno motivacijo (5 min), razlago snovi (15 min), aktivnosti učencev (15 min), utrditev (5 min) in domačo nalogo. Dodaj potrebne materiale.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["učna ura", "načrt", "poučevanje"],
  },
  {
    id: "izob-09",
    categoryId: "izobrazevanje",
    title: "Primerjalna analiza literarnih del",
    prompt: "Napiši primerjalno analizo del [delo 1] in [delo 2]. Primerjaj teme, like, slog pisanja, zgodovinski kontekst in sporočilo. Uporabi citate iz obeh del in zaključi z lastno oceno.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["literatura", "analiza", "primerjava"],
  },
  {
    id: "izob-10",
    categoryId: "izobrazevanje",
    title: "Motivacijsko pismo za vpis",
    prompt: "Napiši prepričljivo motivacijsko pismo za vpis na [program/fakulteta]. Poudari akademske dosežke, relevantne izkušnje, razloge za izbiro programa, karierne cilje in kaj lahko prinesem fakultetni skupnosti. Dolžina: 500 besed.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["motivacijsko pismo", "vpis", "fakulteta"],
  },

  // ═══════════════════════════════════════════
  // KREATIVNO PISANJE (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "krea-01",
    categoryId: "kreativno-pisanje",
    title: "Kratka zgodba z obratom",
    prompt: "Napiši kratko zgodbo (500 besed) z nepričakovanim obratom na koncu. Žanr: [triler/romantika/fantazija/sci-fi]. Zgodba naj ima močan začetek, ki pritegne bralca, in konec, ki preseneti. Uporabi žive opise in dialoge.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["kratka zgodba", "obrat", "fikcija"],
  },
  {
    id: "krea-02",
    categoryId: "kreativno-pisanje",
    title: "Pesem za posebno priložnost",
    prompt: "Napiši pesem v slovenščini za [priložnost: rojstni dan/poroka/novo leto/upokojitev]. Pesem naj ima 4 kitice po 4 verze z rimami (ABAB ali AABB). Ton: [vesel/nostalgičen/slovesen]. Vključi osebne elemente.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["pesem", "poezija", "priložnost"],
  },
  {
    id: "krea-03",
    categoryId: "kreativno-pisanje",
    title: "Scenarij za kratek film",
    prompt: "Napiši scenarij za kratek film (5-7 minut) na temo [tema]. Vključi opis prizorišča, like (2-3), dialoge in režiserske napotke. Format: standardni filmski scenarij. Zgodba naj ima jasno strukturo: zaplet, vrh, razplet.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["scenarij", "film", "dialogi"],
  },
  {
    id: "krea-04",
    categoryId: "kreativno-pisanje",
    title: "Pravljica za otroke",
    prompt: "Napiši pravljico za otroke (starost [3-5/6-8/9-12] let) z naslovom o [tema/lik]. Pravljica naj vsebuje moralno sporočilo o [vrednota: prijateljstvo/pogum/prijaznost]. Vključi ponavljajoče se elemente in srečen konec. Dolžina: 600 besed.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["pravljica", "otroci", "zgodba"],
  },
  {
    id: "krea-05",
    categoryId: "kreativno-pisanje",
    title: "Opis lika za roman",
    prompt: "Ustvari podroben opis lika za roman ali zgodbo. Ime: [ime]. Vključi: fizični opis, osebnostne lastnosti, ozadje (družina, otroštvo), motivacijo, strahove, skrivnost, način govora in razvojni lok skozi zgodbo.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["lik", "razvoj lika", "roman"],
  },
  {
    id: "krea-06",
    categoryId: "kreativno-pisanje",
    title: "Dialog med dvema likoma",
    prompt: "Napiši napeti dialog med dvema likoma: [lik A - opis] in [lik B - opis]. Situacija: [opiši situacijo/konflikt]. Dialog naj razkriva značaje likov, gradi napetost in se zaključi z nepričakovanim odkritjem. Dolžina: 30 replik.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["dialog", "liki", "napetost"],
  },
  {
    id: "krea-07",
    categoryId: "kreativno-pisanje",
    title: "Haiku in kratke pesniške oblike",
    prompt: "Napiši zbirko 10 haikujev v slovenščini na temo [tema: narava/ljubezen/mesto/letni časi]. Vsak haiku naj sledi strukturi 5-7-5 zlogov in ujame poseben trenutek ali občutek. Dodaj kratki komentar k vsakemu.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["haiku", "poezija", "kratka oblika"],
  },
  {
    id: "krea-08",
    categoryId: "kreativno-pisanje",
    title: "Nadaljevanje zgodbe",
    prompt: "Nadaljuj naslednjo zgodbo na kreativen in presenetljiv način. Ohrani slog, ton in razvoj likov. Napiši naslednjih 500 besed. Tukaj je začetek zgodbe: [prilepi začetek]",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["nadaljevanje", "zgodba", "kreativnost"],
  },
  {
    id: "krea-09",
    categoryId: "kreativno-pisanje",
    title: "Monolog dramskega lika",
    prompt: "Napiši dramski monolog (2 minuti govora) za lik [opis lika] v situaciji [opis situacije]. Monolog naj razkrije likovo notranje občutke, dileme in odločitev. Uporabi močne metafore in čustveni lok od dvoma do odločnosti.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["monolog", "drama", "gledališče"],
  },
  {
    id: "krea-10",
    categoryId: "kreativno-pisanje",
    title: "Ideje za zgodbe (brainstorming)",
    prompt: "Generiraj 10 edinstvenih idej za kratke zgodbe. Za vsako idejo napiši: naslov, žanr, povzetek v 2 stavkih, glavnega lika in ključni konflikt. Ideje naj bodo raznolike — od realizma do fantazije, od komedije do drame.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["ideje", "brainstorming", "zgodbe"],
  },

  // ═══════════════════════════════════════════
  // DRUŽBENA OMREŽJA (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "druz-01",
    categoryId: "druzbena-omrezja",
    title: "Instagram objava z opisi",
    prompt: "Napiši 5 Instagram objav za [blagovna znamka/tema]. Za vsako objavo pripravi: besedilo (do 2200 znakov) z emojiji, 5 relevantnih hashtagov, predlog za vizual (opis slike) in CTA. Ton: [profesionalen/sproščen/zabaven].",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["Instagram", "objava", "hashtagi"],
  },
  {
    id: "druz-02",
    categoryId: "druzbena-omrezja",
    title: "LinkedIn članek",
    prompt: "Napiši profesionalen LinkedIn članek (600 besed) na temo [tema]. Začni z vpadljivo kljukico v prvem stavku. Uporabi kratke odstavke, alineje in osebne izkušnje. Zaključi s vprašanjem za spodbujanje komentarjev.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["LinkedIn", "članek", "profesionalno"],
  },
  {
    id: "druz-03",
    categoryId: "druzbena-omrezja",
    title: "TikTok scenarij",
    prompt: "Napiši scenarij za TikTok video (30-60 sekund) na temo [tema]. Vključi: kljukico za prvih 3 sekunde, strukturo vsebine, besedilo za voiceover, predloge za vizualne elemente in trending zvok/glasbo. Format naj bo trendu prilagojen.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["TikTok", "video", "scenarij"],
  },
  {
    id: "druz-04",
    categoryId: "druzbena-omrezja",
    title: "YouTube naslov in opis",
    prompt: "Pripravi 5 predlogov naslovov za YouTube video o [tema]. Za vsak naslov napiši tudi opis videa (500 znakov) z relevantnimi ključnimi besedami, časovnimi značkami (timestamps) in CTA za naročnino. Naslovi naj spodbujajo klik.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["YouTube", "naslov", "opis", "SEO"],
  },
  {
    id: "druz-05",
    categoryId: "druzbena-omrezja",
    title: "Strategija družbenih omrežij",
    prompt: "Pripravi strategijo prisotnosti na družbenih omrežjih za [podjetje/blagovna znamka]. Vključi: izbor platform, tonalnost komuniciranja, tipe vsebin (40-30-20-10 pravilo), pogostost objavljanja, strategijo hashtag-ov in cilje za 3 mesece.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["strategija", "družbena omrežja", "načrt"],
  },
  {
    id: "druz-06",
    categoryId: "druzbena-omrezja",
    title: "Odgovori na komentarje",
    prompt: "Pripravi vzorčne odgovore na komentarje na družbenih omrežjih za [blagovna znamka]. Napiši po 3 odgovore za: pozitivni komentar, pritožbo, vprašanje o ceni, primerjavo s konkurenco in spam. Ton: profesionalen a prijazen.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["komentarji", "odgovori", "community management"],
  },
  {
    id: "druz-07",
    categoryId: "druzbena-omrezja",
    title: "Instagram Reels ideje",
    prompt: "Generiraj 10 idej za Instagram Reels za [blagovna znamka/niša]. Za vsako idejo napiši: naslov, kratki opis vsebine (3 stavki), predlagani zvok/glasba, dolžina in pričakovani učinek. Ideje naj sledijo aktualnim trendom.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["Reels", "Instagram", "ideje", "video"],
  },
  {
    id: "druz-08",
    categoryId: "druzbena-omrezja",
    title: "Bio za družbena omrežja",
    prompt: "Napiši 5 različic kratkega opisa profila (bio) za [oseba/podjetje] na [Instagram/LinkedIn/TikTok/Twitter]. Vsaka bio naj vsebuje: kaj počnemo, za koga, USP in CTA. Max dolžina: 150 znakov za Instagram, 220 za LinkedIn.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["bio", "profil", "družbena omrežja"],
  },
  {
    id: "druz-09",
    categoryId: "druzbena-omrezja",
    title: "Anketa in interaktivna vsebina",
    prompt: "Pripravi 5 interaktivnih vsebin za Instagram Stories za [blagovna znamka]. Vključi: 2 anketi, 1 kviz, 1 drsnik z emojiji in 1 vprašanje. Vsebine naj spodbujajo angažiranost in so povezane s [tematika].",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["anketa", "Stories", "interakcija"],
  },
  {
    id: "druz-10",
    categoryId: "druzbena-omrezja",
    title: "Pinterest opisi pinov",
    prompt: "Napiši opise za 10 Pinterest pinov za [tematika/niša]. Vsak opis naj vsebuje: privlačen naslov (60 znakov), opis z ključnimi besedami (500 znakov) in 5 relevantnih hashtagov. Opisi naj spodbujajo klik na povezavo.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["Pinterest", "pini", "opisi"],
  },

  // ═══════════════════════════════════════════
  // E-POŠTA (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "epos-01",
    categoryId: "e-posta",
    title: "Hladen prodajni e-mail",
    prompt: "Napiši prepričljiv hladen prodajni e-mail za [izdelek/storitev] namenjen [ciljna skupina]. E-mail naj vsebuje: osebno naslavljanje, kljukico v prvem stavku, predstavitev problema, našo rešitev, socialni dokaz in jasen CTA. Dolžina: do 150 besed.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["hladen e-mail", "prodaja", "outreach"],
  },
  {
    id: "epos-02",
    categoryId: "e-posta",
    title: "Newsletter za mesečne novice",
    prompt: "Napiši mesečni newsletter za [podjetje/blagovna znamka]. Vključi: privlačen naslov, pozdrav, 3 glavne novice z kratkimi opisi, nasvet meseca, prihajajočo ponudbo in poziv k akciji. Ton naj bo prijazen in informativen.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["newsletter", "glasilo", "mesečno"],
  },
  {
    id: "epos-03",
    categoryId: "e-posta",
    title: "Sledilno sporočilo (follow-up)",
    prompt: "Napiši serijo 3 sledilnih e-mailov po [sestanek/ponudba/demo]. E-mail 1 (isti dan): zahvala in povzetek. E-mail 2 (po 3 dneh): dodatna vrednost. E-mail 3 (po 7 dneh): zadnji follow-up z novo ponudbo. Vsak do 100 besed.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["follow-up", "sledilno", "prodaja"],
  },
  {
    id: "epos-04",
    categoryId: "e-posta",
    title: "E-mail za ponovni kontakt",
    prompt: "Napiši e-mail za ponovni kontakt s stranko, ki že dolgo ni bila aktivna. Sporočilo naj bo osebno, brez pritiska. Vključi: referenco na prejšnje sodelovanje, novosti v naši ponudbi, posebno ponudbo za vrnitev in prijazen CTA.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["reaktivacija", "stranka", "ponovni kontakt"],
  },
  {
    id: "epos-05",
    categoryId: "e-posta",
    title: "Potrditveni e-mail za naročilo",
    prompt: "Napiši profesionalen potrditveni e-mail za naročilo v spletni trgovini [ime]. Vključi: zahvalo, številko naročila, seznam izdelkov, skupno ceno, predvideni čas dostave, podatke za sledenje in kontakt za pomoč.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["potrditev", "naročilo", "transakcija"],
  },
  {
    id: "epos-06",
    categoryId: "e-posta",
    title: "Vabilo na dogodek",
    prompt: "Napiši privlačno e-mail vabilo na [vrsta dogodka: webinar/konferenca/delavnica]. Vključi: naslov dogodka, datum in uro, lokacijo/povezavo, program/govorce, koristi udeležbe, ceno in CTA za prijavo. Ustvari občutek nujnosti.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["vabilo", "dogodek", "webinar"],
  },
  {
    id: "epos-07",
    categoryId: "e-posta",
    title: "Opravičilo stranki",
    prompt: "Napiši profesionalen e-mail za opravičilo stranki zaradi [problem: zamuda/napaka/slaba izkušnja]. E-mail naj vsebuje: iskreno opravičilo, priznanje problema, razlago (brez izgovorov), korektivne ukrepe, kompenzacijo in zagotovilo za prihodnost.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["opravičilo", "reklamacija", "stranka"],
  },
  {
    id: "epos-08",
    categoryId: "e-posta",
    title: "Prošnja za priporočilo",
    prompt: "Napiši prijazen e-mail, s katerim prosiš zadovoljno stranko za priporočilo ali oceno. Vključi: zahvalo za sodelovanje, kratko omembo uspešnega projekta, prošnjo za oceno (Google/Trustpilot), enostaven postopek in zahvalo vnaprej.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["priporočilo", "ocena", "zadovoljstvo"],
  },
  {
    id: "epos-09",
    categoryId: "e-posta",
    title: "Ponudba s časovno omejitvijo",
    prompt: "Napiši prodajni e-mail s posebno ponudbo, ki ima časovno omejitev. Izdelek/storitev: [opiši]. Popust: [%]. Rok: [datum]. Uporabi psihologijo nujnosti (FOMO), jasne prednosti, pričevanje stranke in vpadljiv CTA gumb.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["ponudba", "urgentnost", "popust"],
  },
  {
    id: "epos-10",
    categoryId: "e-posta",
    title: "Sekvenca onboardinga",
    prompt: "Pripravi sekvenco 5 onboarding e-mailov za novo stranko [storitev/SaaS]. E-mail 1: Dobrodošlica. E-mail 2: Začetni koraki. E-mail 3: Napreden nasvet. E-mail 4: Zgodba uspeha stranke. E-mail 5: Ponudba nadgradnje. Za vsakega napiši zadevo in vsebino.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["onboarding", "sekvenca", "SaaS"],
  },

  // ═══════════════════════════════════════════
  // SEO IN SPLET (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "seo-01",
    categoryId: "seo-in-splet",
    title: "SEO blog objava",
    prompt: "Napiši SEO-optimizirano blog objavo (1500 besed) na temo [tema]. Ciljna ključna beseda: [ključna beseda]. Vključi: privlačen naslov z ključno besedo, uvod s kljukico, vsaj 5 podrazdelkov s H2 naslovi, notranje in zunanje povezave, meta opis in zaključek s CTA.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["blog", "SEO", "ključne besede"],
  },
  {
    id: "seo-02",
    categoryId: "seo-in-splet",
    title: "Meta opisi za strani",
    prompt: "Napiši meta opise (do 160 znakov) za naslednje strani spletne strani: [navedi strani]. Vsak meta opis naj vsebuje ciljno ključno besedo, prednost za obiskovalca in CTA. Dodaj tudi priporočene title tage (do 60 znakov).",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["meta opis", "SEO", "title tag"],
  },
  {
    id: "seo-03",
    categoryId: "seo-in-splet",
    title: "Raziskava ključnih besed",
    prompt: "Opravi raziskavo ključnih besed za [niša/tema] v slovenskem jeziku. Za vsako ključno besedo oceni: iskalni namen (informacijski/transakcijski/navigacijski), težavnost rangiranja (nizka/srednja/visoka) in predlagaj tip vsebine. Navedi vsaj 30 ključnih besed.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["ključne besede", "raziskava", "SEO"],
  },
  {
    id: "seo-04",
    categoryId: "seo-in-splet",
    title: "Vsebinska strategija za blog",
    prompt: "Pripravi 3-mesečno vsebinsko strategijo za blog [ime spletne strani]. Vključi: cilje (promet, konverzije), 12 tem za članke (1 na teden), ključne besede za vsak članek, tip vsebine (vodnik/seznam/analiza) in strategijo promocije.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["vsebinska strategija", "blog", "načrt"],
  },
  {
    id: "seo-05",
    categoryId: "seo-in-splet",
    title: "Preoblikovanje starega članka",
    prompt: "Preoblikuj in posodobi naslednji članek za boljše SEO rezultate. Dodaj aktualne informacije, izboljšaj strukturo naslovov, dodaj ključne besede naravno, optimiziraj za featured snippet in dodaj FAQ razdelek. Tukaj je članek: [prilepi članek]",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["preoblikovanje", "posodobitev", "SEO"],
  },
  {
    id: "seo-06",
    categoryId: "seo-in-splet",
    title: "FAQ stran za spletno stran",
    prompt: "Napiši FAQ stran (15 vprašanj in odgovorov) za spletno stran [ime/dejavnost]. Vprašanja naj odražajo resnične iskalne poizvedbe. Odgovori naj bodo jedrnati (50-100 besed), informatvni in SEO-optimizirani. Strukturiraj za FAQ schema markup.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["FAQ", "schema", "spletna stran"],
  },
  {
    id: "seo-07",
    categoryId: "seo-in-splet",
    title: "Naslovi za blog objave",
    prompt: "Generiraj 20 privlačnih naslovov za blog objave na temo [tema]. Uporabi dokazane formule: številke, vprašanja, 'kako', seznami, primerjave. Za vsak naslov dodaj ciljno ključno besedo in oceni CTR potencial (nizek/srednji/visok).",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["naslovi", "blog", "CTR"],
  },
  {
    id: "seo-08",
    categoryId: "seo-in-splet",
    title: "Lokalni SEO — Google My Business",
    prompt: "Napiši optimiziran opis za Google My Business profil za [podjetje] v [mesto]. Vključi: poslovni opis (750 znakov), 5 objav za GMB (kratke, z CTA), predloge za kategorije, in nasvete za zbiranje ocen. Vse v slovenščini.",
    tool: "ai-besedila",
    toolLabel: "AI Besedila",
    tags: ["lokalni SEO", "Google My Business", "lokalno"],
  },
  {
    id: "seo-09",
    categoryId: "seo-in-splet",
    title: "Struktura spletne strani (sitemap)",
    prompt: "Predlagaj optimalno strukturo spletne strani za [dejavnost]. Vključi: hierarhijo strani (glavne, podstrani), URL strukturo, navigacijo, notranje povezave in priporočila za SEO. Predstavi v obliki drevesne strukture.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["struktura", "sitemap", "navigacija"],
  },
  {
    id: "seo-10",
    categoryId: "seo-in-splet",
    title: "Besedila za pristajalno stran",
    prompt: "Napiši konverzijsko optimizirana besedila za pristajalno stran za [izdelek/storitev]. Vključi: hero naslov in podnaslov, 3 prednosti z opisi, razdelek 'Kako deluje' (3 koraki), pričevanja (3), cenovni razdelek, FAQ (5 vprašanj) in CTA.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["pristajalna stran", "konverzija", "CRO"],
  },

  // ═══════════════════════════════════════════
  // GRAFIKA (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "graf-01",
    categoryId: "grafika",
    title: "Logotip za podjetje",
    prompt: "Ustvari minimalističen logotip za podjetje z imenom [ime podjetja] v panogi [panoga]. Logotip naj bo moderen, čist in prepoznaven. Uporabi [barve] in geometrijske oblike. Slog: flat design, primeren za digitalno in tiskano uporabo.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["logotip", "branding", "dizajn"],
  },
  {
    id: "graf-02",
    categoryId: "grafika",
    title: "Banner za družbena omrežja",
    prompt: "Ustvari privlačen banner za [Instagram/Facebook/LinkedIn] za [podjetje/kampanja]. Vključi besedilo '[naslov]' v modernem fontu, barvno paleto [barve], in elemente povezane z [tematika]. Razmerje: 1:1 za Instagram, 16:9 za Facebook cover.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["banner", "družbena omrežja", "vizual"],
  },
  {
    id: "graf-03",
    categoryId: "grafika",
    title: "Ilustracija za blog",
    prompt: "Ustvari ilustracijo za blog članek na temo [tema]. Slog: [flat illustration/watercolor/line art/isometric]. Barvna paleta: [barve]. Ilustracija naj bo čista, moderna in primerna za spletno uporabo. Brez besedila na sliki.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["ilustracija", "blog", "splet"],
  },
  {
    id: "graf-04",
    categoryId: "grafika",
    title: "Vizitka — dizajn",
    prompt: "Ustvari dizajn vizitke za [ime in naziv] iz podjetja [podjetje]. Sprednja stran: logotip, ime, naziv, kontakt. Zadnja stran: minimalistični vzorec. Barve: [barve]. Slog: moderen, profesionalen, z dovolj praznega prostora.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["vizitka", "dizajn", "tiskovine"],
  },
  {
    id: "graf-05",
    categoryId: "grafika",
    title: "Mockup izdelka",
    prompt: "Ustvari fotorealističen prikaz izdelka [opis izdelka] v okolju [opis okolja]. Izdelek naj bo v središču pozornosti z mehko svetlobo in subtilnimi sencami. Ozadje: [barva/tekstura]. Perspektiva: [tloris/3D pogled/lifestyle].",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["mockup", "izdelek", "fotorealizem"],
  },
  {
    id: "graf-06",
    categoryId: "grafika",
    title: "Infografika",
    prompt: "Ustvari vizualno privlačno infografiko na temo [tema]. Vključi [število] ključnih podatkov, ikone, grafikone in barvno paleto [barve]. Slog: moderen, čist, lahek za branje. Vertikalna usmeritev, primerna za Pinterest ali blog.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["infografika", "podatki", "vizualizacija"],
  },
  {
    id: "graf-07",
    categoryId: "grafika",
    title: "Ozadje za spletno stran",
    prompt: "Ustvari abstraktno ozadje za spletno stran v temni temi. Barve: odtenki [barve] na temnem ozadju (#171717). Slog: subtilni geometrijski vzorci, gradient mesh ali mehki valovi. Brez besedila. Visoka ločljivost, primerno za hero sekcijo.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["ozadje", "spletna stran", "abstraktno"],
  },
  {
    id: "graf-08",
    categoryId: "grafika",
    title: "Ikona za aplikacijo",
    prompt: "Ustvari ikono za mobilno aplikacijo [ime aplikacije] — [opis funkcije]. Ikona naj bo preprosta, prepoznavna pri majhni velikosti (1024x1024px). Uporabi [barve] in zaobljeni kvadrat. Slog: iOS/Android app icon guidelines.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["ikona", "aplikacija", "mobilno"],
  },
  {
    id: "graf-09",
    categoryId: "grafika",
    title: "Sezonska grafika",
    prompt: "Ustvari praznično grafiko za [praznik: Novo leto/Valentinovo/Velika noč/Božič] za blagovno znamko [ime]. Vključi praznične elemente, barvno paleto praznika in prostor za besedilo. Slog: eleganten, moderen, ne preveč kičast.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["praznik", "sezonsko", "grafika"],
  },
  {
    id: "graf-10",
    categoryId: "grafika",
    title: "Portret v umetniškem slogu",
    prompt: "Ustvari umetniški portret osebe v slogu [pop art/akvarel/olje na platnu/digitalna umetnost/anime]. Oseba: [opis]. Ozadje: [opis]. Osvetlitev: [naravna/dramatična/studijska]. Kompozicija: [doprsni/celofigurni]. Visoka detajlnost obraza.",
    tool: "ai-grafika",
    toolLabel: "AI Grafika",
    tags: ["portret", "umetnost", "slog"],
  },

  // ═══════════════════════════════════════════
  // ZVOK (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "zvok-01",
    categoryId: "zvok",
    title: "Scenarij za podkast epizodo",
    prompt: "Napiši scenarij za podkast epizodo (20 minut) na temo [tema]. Vključi: uvod z jingle opisom (30s), predstavitev teme, 3 glavne točke z primeri, intervju vprašanja (če je gost), povzetek in zaključek s CTA za naročnino.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["podkast", "scenarij", "epizoda"],
  },
  {
    id: "zvok-02",
    categoryId: "zvok",
    title: "Voiceover za promocijski video",
    prompt: "Napiši besedilo za voiceover promocijskega videa (60 sekund) za [izdelek/storitev]. Tempo: 150 besed/minuto. Začni z vprašanjem, predstavi problem, ponudi rešitev, navedi 3 prednosti in zaključi s CTA. Ton: [profesionalen/navdušen/miren].",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["voiceover", "video", "promocija"],
  },
  {
    id: "zvok-03",
    categoryId: "zvok",
    title: "Intro za YouTube kanal",
    prompt: "Napiši besedilo za YouTube intro (10-15 sekund) za kanal [ime kanala] o [tematika]. Intro naj bo energičen, zapomljiv in naj jasno pove, kaj gledalec lahko pričakuje. Dodaj tudi predlog za outro besedilo (10 sekund).",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["intro", "YouTube", "outro"],
  },
  {
    id: "zvok-04",
    categoryId: "zvok",
    title: "Radijski oglas",
    prompt: "Napiši scenarij za radijski oglas (30 sekund) za [izdelek/storitev/dogodek]. Vključi: kljukico (prvih 5 sekund), jedro sporočila z glavno prednostjo, ponudbo in CTA s kontaktnimi podatki. Besedilo naj bo naravno za govorjenje.",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["radijski oglas", "avdio", "oglaševanje"],
  },
  {
    id: "zvok-05",
    categoryId: "zvok",
    title: "Meditacijska vaja",
    prompt: "Napiši besedilo za vodeno meditacijo (10 minut) na temo [sproščanje/spanje/fokus/hvaležnost]. Uporabi miren, počasen tempo govora s premori. Vključi: dihalne vaje, vizualizacijo, body scan in nežen zaključek. Ton: pomirjujoč, tih.",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["meditacija", "sproščanje", "vodena"],
  },
  {
    id: "zvok-06",
    categoryId: "zvok",
    title: "Avdio vodnik za muzej",
    prompt: "Napiši besedilo za avdio vodnik po [muzej/razstava/mesto]. Vsebina za 5 postaj, vsaka 2 minuti. Za vsako postajo: opis eksponata/lokacije, zgodovinski kontekst, zanimivosti in prehod na naslednjo postajo. Ton: informativen a zanimiv.",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["avdio vodnik", "muzej", "turizem"],
  },
  {
    id: "zvok-07",
    categoryId: "zvok",
    title: "IVR sporočilo za podjetje",
    prompt: "Napiši besedila za IVR (telefonski odzivnik) za podjetje [ime]. Vključi: pozdravno sporočilo, meni z opcijami (prodaja, podpora, info), sporočilo za čakanje, sporočilo zunaj delovnega časa in sporočilo za odzivnik. Vse kratko in jasno.",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["IVR", "telefon", "odzivnik"],
  },
  {
    id: "zvok-08",
    categoryId: "zvok",
    title: "Napovedovalec za dogodek",
    prompt: "Napiši besedilo za napovedovalca na [vrsta dogodka: konferenca/gala/športni dogodek]. Vključi: otvoritveni nagovor, predstavitev govorcev/nastopajočih, prehodna besedila med točkami programa, zahvale sponzorjem in zaključni govor.",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["napovedovalec", "dogodek", "vodenje"],
  },
  {
    id: "zvok-09",
    categoryId: "zvok",
    title: "Besedilo za e-learning",
    prompt: "Napiši besedilo za e-learning modul (10 minut) na temo [tema]. Razdeli na 5 lekcij po 2 minuti. Vsaka lekcija: uvod, razlaga s primeri, povzetek ključnih točk. Ton: jasen, prijazen, poučen. Dodaj vprašanja za preverjanje po vsaki lekciji.",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["e-learning", "izobraževanje", "modul"],
  },
  {
    id: "zvok-10",
    categoryId: "zvok",
    title: "Govorna sinteza za novo vsebino",
    prompt: "Pretvori naslednje besedilo v obliko, primerno za govorno sintezo (TTS). Poenostavi dolge stavke, dodaj naravne premore (vejice), zamenjaj kratice z izgovorjenimi besedami, dodaj fonetične zapise za tuje besede. Besedilo: [prilepi besedilo]",
    tool: "ai-zvok",
    toolLabel: "AI Zvok",
    tags: ["TTS", "govorna sinteza", "pretvorba"],
  },

  // ═══════════════════════════════════════════
  // PRODUKTIVNOST (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "prod-01",
    categoryId: "produktivnost",
    title: "Zapisnik sestanka",
    prompt: "Pripravi strukturiran zapisnik sestanka. Datum: [datum]. Udeleženci: [imena]. Na podlagi mojih zapiskov napiši: dnevni red, ključne razprave po točkah, sprejete odločitve, akcijski načrt (kdo, kaj, do kdaj) in datum naslednjega sestanka. Moji zapiski: [prilepi zapiske]",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["zapisnik", "sestanek", "organizacija"],
  },
  {
    id: "prod-02",
    categoryId: "produktivnost",
    title: "Projektni načrt",
    prompt: "Pripravi podroben projektni načrt za [ime projekta]. Vključi: cilje projekta, obseg (scope), razdelitev na faze (4-6 faz), naloge za vsako fazo, odgovorne osebe, mejnike (milestones), tveganja in časovnico. Format: pregledna tabela.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["projektni načrt", "faze", "upravljanje"],
  },
  {
    id: "prod-03",
    categoryId: "produktivnost",
    title: "Tedenski načrt opravil",
    prompt: "Na podlagi mojih prioritet pripravi strukturiran tedenski načrt. Prioritete: [navedi naloge]. Za vsak dan (pon-pet) razporedi naloge z ocenjenim časom, dodaj časovne bloke za globoko delo, sestanke in premore. Upoštevaj pravilo 80/20.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["tedenski načrt", "opravila", "produktivnost"],
  },
  {
    id: "prod-04",
    categoryId: "produktivnost",
    title: "SMART cilji",
    prompt: "Pomagaj mi preoblikovati naslednje nejasne cilje v SMART cilje (specifični, merljivi, dosegljivi, relevantni, časovno omejeni). Moji cilji: [navedi cilje]. Za vsak cilj napiši SMART verzijo, ključne metrike in prve 3 korake za dosego.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["SMART cilji", "načrtovanje", "cilje"],
  },
  {
    id: "prod-05",
    categoryId: "produktivnost",
    title: "Dnevno poročilo o napredku",
    prompt: "Pripravi predlogo dnevnega poročila o napredku za ekipo. Vključi: opravljene naloge danes, naloge v teku, blokirane naloge (z razlogom), načrt za jutri in ključne metrike. Format naj bo kratek in pregleden za hiter pregled.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["dnevno poročilo", "napredek", "ekipa"],
  },
  {
    id: "prod-06",
    categoryId: "produktivnost",
    title: "Agenda za sestanek",
    prompt: "Pripravi agendo za sestanek na temo [tema sestanka]. Trajanje: [čas]. Udeleženci: [imena]. Vključi: cilje sestanka, točke dnevnega reda s časovnimi okvirji, odgovorno osebo za vsako točko, materiale za pripravo in prostor za sklepe.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["agenda", "sestanek", "načrtovanje"],
  },
  {
    id: "prod-07",
    categoryId: "produktivnost",
    title: "Delegiranje nalog",
    prompt: "Pomagaj mi delegirati naslednje naloge v ekipi. Naloge: [navedi naloge]. Člani ekipe in njihove kompetence: [navedi]. Za vsako nalogo določi: odgovorno osebo, rok, prednostno raven (visoka/srednja/nizka), potrebne resurse in pričakovan rezultat.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["delegiranje", "ekipa", "naloge"],
  },
  {
    id: "prod-08",
    categoryId: "produktivnost",
    title: "Retrospektiva sprinta",
    prompt: "Pripravi strukturo za retrospektivo sprinta. Vključi razdelke: Kaj je šlo dobro? Kaj bi lahko izboljšali? Kaj bomo spremenili? Za vsak razdelek pripravi 3 vodilna vprašanja. Dodaj predlogo za akcijski načrt izboljšav z odgovornimi osebami.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["retrospektiva", "sprint", "agile"],
  },
  {
    id: "prod-09",
    categoryId: "produktivnost",
    title: "Eisenhower matrika prioritet",
    prompt: "Pomagaj mi razvrstiti naslednje naloge v Eisenhower matriko (nujno/pomembno). Naloge: [navedi vse naloge]. Za vsako nalogo določi kvadrant, priporočeno akcijo (naredi/planiraj/delegiraj/eliminiraj) in kratko obrazložitev. Rezultat predstavi kot 2x2 tabelo.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["prioritete", "Eisenhower", "odločanje"],
  },
  {
    id: "prod-10",
    categoryId: "produktivnost",
    title: "SOP — standardni postopek",
    prompt: "Napiši standardni operativni postopek (SOP) za [proces/naloga]. Vključi: namen postopka, obseg, odgovorne osebe, potrebno opremo/dostop, korak-za-korakom navodila (oštevilčena), pogosta odstopanja in rešitve, ter revizijsko tabelo.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["SOP", "postopek", "dokumentacija"],
  },

  // ═══════════════════════════════════════════
  // DIY IN ŽIVLJENJSKI SLOG (10 prompts)
  // ═══════════════════════════════════════════
  {
    id: "diy-01",
    categoryId: "diy-zivljenjski-slog",
    title: "Recept za jed",
    prompt: "Napiši podroben recept za [ime jedi ali opis: npr. 'kremna gobova juha']. Vključi: opis jedi (2 stavka), čas priprave in kuhanja, število porcij, seznam sestavin z gramaturami, korak-za-korakom navodila, nasvete za postrežbo in hranilno vrednost.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["recept", "kuhanje", "jed"],
  },
  {
    id: "diy-02",
    categoryId: "diy-zivljenjski-slog",
    title: "Tedenski jedilnik",
    prompt: "Pripravi uravnotežen tedenski jedilnik (pon-ned) za [število oseb]. Preferenco: [normalna/vegetarijanska/veganska/brez glutena]. Za vsak dan: zajtrk, malica, kosilo, malica, večerja. Dodaj nakupovalni seznam sestavin razvrščen po oddelkih trgovine.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["jedilnik", "tedenski", "prehrana"],
  },
  {
    id: "diy-03",
    categoryId: "diy-zivljenjski-slog",
    title: "Vodnik za domači projekt",
    prompt: "Napiši podroben vodnik za domači DIY projekt: [opis projekta, npr. 'lesena polica za knjige']. Vključi: seznam materiala in orodja, varnostna opozorila, korak-za-korakom navodila s slikami (opisi), ocenjeni čas in stroške ter nasvete za začetnike.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["DIY", "domači projekt", "navodila"],
  },
  {
    id: "diy-04",
    categoryId: "diy-zivljenjski-slog",
    title: "Načrt potovanja",
    prompt: "Pripravi podroben načrt potovanja v [destinacija] za [število dni] dni. Vključi: dnevni razpored z aktivnostmi, priporočene nastanitve, lokalne restavracije, transportne možnosti, ocenjeni proračun, nasvete za pakiranje in kulturne posebnosti.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["potovanje", "načrt", "itinerarij"],
  },
  {
    id: "diy-05",
    categoryId: "diy-zivljenjski-slog",
    title: "Fitnes program za 4 tedne",
    prompt: "Pripravi 4-tedenski fitnes program za [cilj: hujšanje/pridobivanje mišic/vzdržljivost/splošna kondicija]. Raven: [začetnik/srednji/napreden]. Za vsak teden: 5 treningov z vajami, serijami, ponovitvami, odmori in napredovanjem. Dodaj nasvete za regeneracijo.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["fitnes", "program", "vadba"],
  },
  {
    id: "diy-06",
    categoryId: "diy-zivljenjski-slog",
    title: "Načrt vrta za sezono",
    prompt: "Pripravi načrt za vrt za [vrsta: zelenjavni/cvetlični/zeliščni] vrt. Velikost: [m2]. Lokacija: Slovenija. Vključi: razpored sajenja po mesecih, združljivost rastlin, gnojenje, zalivanje, zaščito pred škodljivci in pričakovani pridelek.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["vrt", "vrtnarjenje", "sezona"],
  },
  {
    id: "diy-07",
    categoryId: "diy-zivljenjski-slog",
    title: "Organizacija doma — KonMari",
    prompt: "Pripravi načrt za organizacijo [prostor: kuhinja/garderoba/pisarna/garaža] po KonMari metodi. Vključi: korake za čiščenje, sistem kategorizacije, priporočene organizacijske pripomočke, nasvete za vzdrževanje reda in kontrolni seznam.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["organizacija", "dom", "čiščenje"],
  },
  {
    id: "diy-08",
    categoryId: "diy-zivljenjski-slog",
    title: "Načrt za praznovanje",
    prompt: "Pripravi podroben načrt za praznovanje [dogodek: rojstni dan/obletnica/novo leto/BBQ zabava] za [število gostov] gostov. Vključi: temo zabave, seznam opravil (časovnica), meni, dekoracijo, aktivnosti/igre, glasbo in proračun.",
    tool: "ai-dokumenti",
    toolLabel: "AI Dokumenti",
    tags: ["praznovanje", "zabava", "načrt"],
  },
  {
    id: "diy-09",
    categoryId: "diy-zivljenjski-slog",
    title: "Osebni finančni načrt",
    prompt: "Pomagaj mi pripraviti osebni finančni načrt. Mesečni prihodek: [znesek]. Cilji: [navedi cilje]. Pripravi: pregled prihodkov in odhodkov, priporočeno razdelitev (50/30/20 pravilo), varčevalni načrt, strategijo odplačila dolgov in nasvete za investiranje.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["finance", "proračun", "varčevanje"],
  },
  {
    id: "diy-10",
    categoryId: "diy-zivljenjski-slog",
    title: "Jutranja rutina za produktivnost",
    prompt: "Pripravi optimalno jutranjo rutino (60-90 minut) za povečanje produktivnosti in dobrega počutja. Vključi: uro bujenja, aktivnosti po korakih s trajanjem, razlago koristi vsake aktivnosti, nasvete za navajanje in prilagoditve za vikende.",
    tool: "ai-chat",
    toolLabel: "AI Chat",
    tags: ["jutranja rutina", "produktivnost", "navade"],
  },
];

// Helper functions
export function getPromptsByCategory(categoryId: string): Prompt[] {
  return allPrompts.filter((p) => p.categoryId === categoryId);
}

export function searchPrompts(query: string): Prompt[] {
  const lower = query.toLowerCase();
  return allPrompts.filter(
    (p) =>
      p.title.toLowerCase().includes(lower) ||
      p.prompt.toLowerCase().includes(lower) ||
      p.tags.some((t) => t.toLowerCase().includes(lower))
  );
}

export function getPromptsByTool(tool: string): Prompt[] {
  return allPrompts.filter((p) => p.tool === tool);
}
